### PR TITLE
Add nullish coalescing support

### PR DESCRIPTION
**Pull request by Chocohead**
Based on the suggestion in #35. Should work™, but haven't tested yet.

### CODE REVIEW

**Comment by buttercookie42** [comment]
Nice. I was looking at trying to apply those patches myself, but was still in the middle of getting a PGO build going.

One wish regarding future source code archeology: Could you include the notes which Bugzilla bugs this was ported from in the commit message (i.e. assuming it's [this patch](https://src.fedoraproject.org/rpms/seamonkey/blob/39f13400/f/seamonkey-2.53.10-nullish-coalesce.patch), bugs 1566141 part 1-3 and 5-8, 1593415 and 1599163)?

**Comment by buttercookie42** [comment]
I'm hitting a build error with this:

```
 2:51.16 In file included from c:/Waterfox/Waterfox-Classic/js/src/jsarray.cpp:7:
 2:51.16 In file included from c:/Waterfox/Waterfox-Classic/js/src/jsarrayinlines.h:16:
 2:51.16 In file included from c:/Waterfox/Waterfox-Classic/js/src/vm/ArgumentsObject-inl.h:14:
 2:51.16 In file included from c:/Waterfox/Waterfox-Classic/js/src/jsscriptinlines.h:13:
 2:51.16 In file included from c:/Waterfox/Waterfox-Classic/js/src/jit/IonAnalysis.h:13:
 2:51.16 c:/Waterfox/Waterfox-Classic/js/src/jit/MIR.h(13183,11): error: no matching constructor for initialization of 'js::jit::MUnaryInstruction'
 2:51.16         : MUnaryInstruction(classOpcode, value) {
 2:51.16           ^                 ~~~~~~~~~~~~~~~~~~
 2:51.16 c:/Waterfox/Waterfox-Classic/js/src/jit/MIR.h(1288,14): note: candidate constructor not viable: requires single argument 'ins', but 2 arguments were provided
 2:51.16     explicit MUnaryInstruction(MDefinition* ins)
 2:51.16              ^
 2:51.16 c:/Waterfox/Waterfox-Classic/js/src/jit/MIR.h(1285,7): note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
 2:51.16 class MUnaryInstruction : public MAryInstruction<1>
 2:51.16       ^
 2:51.16 c:/Waterfox/Waterfox-Classic/js/src/jit/MIR.h(1285,7): note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
 2:51.16 1 error generated.
 2:51.16 mozmake.EXE[5]: *** [c:/Waterfox/Waterfox-Classic/config/rules.mk;1033: jsarray.obj] Error 1
```

**Comment by Chocohead** [comment]
Not sure how I managed to miss committing that line the first time, updated the message too

**Comment by buttercookie42** [comment]
I've noticed that backported patches for this have also appeared in the [official repository for Seamonkey 2.53](https://gitlab.com/seamonkey-project/seamonkey-2.53-mozilla/-/commits/2_53_12_final/js/src/frontend/) ([originally here](https://gitlab.com/frg/seamonkey-253-patches/-/commit/f66b99df8e6ea43b840161046ed77ffb1b888a82)). I haven't extensively compared them, but did immediately notice that the older patch based on https://src.fedoraproject.org/rpms/seamonkey/tree/39f13400 I guess (?) is e.g. missing some bits in ReflectParse.cpp. I guess they're not crucial to most everyday usage of the coalescing operator, but it still seems a little suspicious.

Out of curiosity I'm trying to see if I can backport the "official" Seamonkey patches, although that does mean backporting quite a few other Seamonkey backports for SpiderMonkey, too, which I'm currently right in the middle of…

**Comment by buttercookie42** [comment]
I've also finally finished my project to attempt this based on the "official" Seamonkey 2.53.12 patches, which basically involved backporting [most of the Spidermonkey frontend changes listed here](https://gitlab.com/seamonkey-project/seamonkey-2.53-mozilla/-/commits/2_53_12_final/js/src/frontend/), plus a few bits in other parts of the JS engine code.

The only problem is that what with all the additional backports the whole thing amounts to 145 commits. Because Github doesn't support stacked pull requests across forks and I've already got the similarly ginormous Windows PGO pull request (#104) up in a holding pattern, I've temporarily [put them up here](https://github.com/buttercookie42/Waterfox-Classic/tree/nullish) – ~~note that that branch includes all my other WIP changesets as well, though. The proper subset that is "just" the various backports plus the nullish operator [is this one](https://github.com/buttercookie42/Waterfox-Classic/compare/misc...buttercookie42:nullish).~~ (Edit: No longer applies, as the commits have been re-ordered in preparation for the pull requests)

**Comment by Sa-Ja-Di** [comment]
https://repo.palemoon.org/MoonchildProductions/UXP/pulls/1901

Was successfully implemented in Pale Moon and can be revisited for Waterfox Classic too!

**Comment by buttercookie42** [comment]
Put up #124, apologies to @Chocohead for duplicating your work.

**Comment by Chocohead** [comment]
No bother, a comprehensive port is probably better anyway

**Pull request closed without merging**
