### PR TITLE
Fix build issues

### PR DESCRIPTION
**Pull request by hawkeye116477**

### CODE REVIEW

**Comment by hawkeye116477** [comment]
It's not all, it still displays errors and works only fine after reverting all Bug 1667102 changes.

**Comment by MrAlex94** [comment]
I was thinking of pulling this in but still pinning the rust version - saves the builders from dying if there's another rust update that's incompatible with the existing rust code?

**Comment by hawkeye116477** [comment]
Ok, fixed.

**Comment by MrAlex94** [comment]
Thank you!

**Pull request merged**
